name: build
on:
  push:
    paths:
      - "src/client/**"
      - "build.gradle"

jobs:
  build:
    strategy:
      matrix:
        java: [ 21, ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: gen name
        run: |
          archivesBaseName=$(grep 'archives_base_name' gradle.properties | sed 's/archives_base_name=//' | sed 's/ /_/g')
          version=$(grep 'mod_version' gradle.properties | sed 's/mod_version=//' | sed 's/ /_/g')
          commitHash=$(git rev-parse --short HEAD)
          fileName=$archivesBaseName-$version
          name=$archivesBaseName-$version-$commitHash
          echo "modName"=${archivesBaseName}" >> $GITHUB_ENV 
          echo "fileName=${fileName}" >> $GITHUB_ENV
          echo "name=${name}" >> $GITHUB_ENV

      - name: change file name
        run: |
          mv ./build/libs/${{ env.fileName }}.jar ${{ env.name }}.jar

      - name: get checksum
        run: |
          checksum=$(sha256sum ${{ env.name }}.jar | sed 's/${{ env.name }}.jar//g')
          echo checksum=$checksum >> $GITHUB_ENV

      - name: send to discord
        env:
          runID: ${{ github.run_id }}
          webhookUrl: ${{ secrets.NIGHTLY_DISCORD_WEBHOOK }}
        run: |
          commitMessage=$(git log --pretty=format:"[%h](https://github.com/$GITHUB_REPOSITORY/commit/%H) %s" -1 --reverse)
          json='{"embeds":[{"title":"'${{ env.modName }}-BETA'","url":"https://github.com/'$GITHUB_REPOSITORY'/actions/runs/'$runID'","description":"**sha256sum**\n`${{ env.checksum }}`\n\n**Commit**\n '$commitMessage'","color":65416}]}'
          curl "$webhookUrl" -H "Content-Type:application/json" -X POST -d "$json"
          curl "$webhookUrl" -H "Content-Type:multipart/form-data" -X POST -F "files[0]=@${{ env.name }}.jar"